name: 'nyc_analytics'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  nyc_analytics:
    +materialized: table
    work:
      staging:
        +materialized: table
        +schema: gr_proj_staging
      marts:
        +materialized: table
        +schema: gr_proj_marts
        shared:
          +materialized: table
        drug_activity_311:
          +materialized: table
        shooting_incidents:
          +materialized: table